urls
CREATE TABLE urls(
  id SERIAL PRIMARY KEY,
  url TEXT NOT NULL,
  shortUrl TEXT NOT NULL UNIQUE,
  createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
  clicks INT DEFAULT 0,
  userId INTEGER NOT NULL REFERENCES "users"("id")
)

users
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    password TEXT NOT NULL
)